apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: streamlit
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  to:
    kind: Service
    name: proxy
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
