apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - pvc.yaml
  - route.yaml
  - service.yaml
  # - otel-collector-sidecar.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: run-config
    files:
      - config.yaml=run.yaml
