apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-persist
  annotations:
    openshift.io/description: "Storage for llama stack state"
    argocd.argoproj.io/sync-wave: "5"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
