kind: Deployment
apiVersion: apps/v1
metadata:
  name: ansible-mcp-server
spec:
  selector:
    matchLabels:
      app: ansible-mcp-server
  replicas: 1
  template:
    metadata:
      labels:
        app: ansible-mcp-server
    spec:
      containers:
      - name: ansible-mcp-server
        image: quay.io/redhat-et/mcp-ansible:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
        env:
          - name: AAP_TOKEN
            valueFrom:
              secretKeyRef:
                name: aap
                key: token
          - name: AAP_URL
            valueFrom:
              secretKeyRef:
                name: aap
                key: url
        resources: {}
