kind: Deployment
apiVersion: apps/v1
metadata:
  name: custom-mcp-server
spec:
  selector:
    matchLabels:
      app: custom-mcp-server
  replicas: 1
  template:
    metadata:
      labels:
        app: custom-mcp-server
    spec:
      containers:
      - name: custom-mcp-server
        image: quay.io/rh-ee-anxie/mcp-custom-server:latests
        ports:
          - containerPort: 8000
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
        resources: {}
