kind: Secret
apiVersion: v1
metadata:
  name: llama-32-3b-instruct
  labels:
    opendatahub.io/dashboard: 'true'
  annotations:
    opendatahub.io/connection-type-ref: uri-v1
    openshift.io/description: ''
    openshift.io/display-name: llama-3.2-3b-instruct
    argocd.argoproj.io/sync-wave: "1"
data:
  URI: b2NpOi8vcXVheS5pby9yZWRoYXQtYWktc2VydmljZXMvbW9kZWxjYXItY2F0YWxvZzpsbGFtYS0zLjItM2ItaW5zdHJ1Y3Q=
type: Opaque
